### ISSUE TITLE
Fill out the explanation of each testnet we have

### ISSUE THREAD

**Issue by taiki1frsh** [UnUniFi/gitbook#30]
I added a blank page for the general description of all testnets we have in this PR https://github.com/UnUniFi/gitbook/pull/29.

Please fill out the TODO content if you're familiar with all testnets' role.
@Senna46 @mkXultra

**Comment by Senna46** [comment]
Already created. Please add it here. #28 
https://github.com/UnUniFi/gitbook/blob/feat/dev-tool/develop/resources.md

**Comment by taiki1frsh** [comment]
oh, didn't see it.
Got it
